version: '3.1'
services:
    db:
        image: "postgres:alpine"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: dbuser
            POSTGRES_DB: wegmans