version: 2
jobs:
    build:
        docker:
            - image: node:alpine

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies
            - run: npm ci
            - save_cache:
                key: v1-dependencies0{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run: npm t