version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11.10-browsers

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies
            - run:
                name: Install Dependencies
                command: npm ci
            - save_cache:
                key: v1-dependencies0{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Run Unit Tests
                command: npm run test:ci
                environment:
                    JEST_JUNIT_OUTPUT: "test-reports/junit/results.xml"
            - store_test_results:
                  path: test-reports
