version: 2.1

workflows:
    build-and-test:
        jobs:
            - build
            - unit-test:
                requires:
                    - build
            - integration-test:
                requires:
                    - build
jobs:
    build:
        docker:
            - image: circleci/node:11.10-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - save_cache:
                paths:
                    - ~/repo
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                name: Install Dependencies
                command: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package-lock.json" }}

            - run:
                name: Build Typescript Files
                command: npm run build

    unit-test:
        docker:
            - image: circleci/node:11.10-browsers
        working_directory: ~/repo
        steps:
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Run Unit Tests
                  command: npm run test:ci
                  environment:
                      JEST_JUNIT_OUTPUT: ./test-results/results.xml

            - store_test_results:
                  path: test-results

    integration-test:
        docker:
            - image: circleci/node:11.10-browsers
        working_directory: ~/repo
        steps:
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Run Integration Tests
                  command: npm run test:integration
                  environment:
                      JEST_JUNIT_OUTPUT: ./test-results/results.xml

            - store_test_results:
                  path: test-results
